version: '1'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    networks: [ metrics ]
    ports:
      - '8086:8086'
    volumes:
      - /docker/influxdb/data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=raw
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_USER=${INFLUXDB_USER_USERNAME}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}

  chronograf:
    container_name: chronograf
    restart: always
    image: chronograf:latest
    ports:
      - "8888:8888" # 127.0.0.1:8888:8888 this makes sure this port is only accessible from the localhost
    depends_on:
      - influxdb
    networks: [ metrics ]
    environment:
      - INFLUXDB_URL=http://influxdb:8086 # needs to match container_name
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME} # sourced from .env
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD} # sourced from .env

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - /docker/grafana/data:/var/lib/grafana
      - ./grafana/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
volumes:
  influxdb-storage:
  chronograf-storage:
  grafana-storage: